/**
 * Every word the user reads.
 *
 * ---------------------------------------------------------------------------
 * Why this file exists
 * ---------------------------------------------------------------------------
 * Copy scattered through fifty screens cannot be reviewed, cannot be kept
 * consistent, and cannot be translated. Keeping it here means the client can
 * read the entire product's wording in one pass, and the day a second language
 * is needed the work is already done — this object is the shape a translation
 * file takes.
 *
 * ---------------------------------------------------------------------------
 * Rules for adding copy
 * ---------------------------------------------------------------------------
 * - Group by feature, matching the folder it is used in.
 * - Write from the reader's side of the screen. A dispatcher manages
 *   "drivers", not "user records".
 * - A button says exactly what happens: "Send invitation", then a confirmation
 *   that says "Invitation sent".
 * - Errors say what went wrong and what to do about it. No apologies.
 * - Anything that varies at runtime is a function, so the sentence stays
 *   readable instead of being assembled from fragments at the call site.
 */

export const STRINGS = {
  /** Shared across the whole console. */
  common: {
    appName: 'B2bSamsaraFleet',
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    close: 'Close',
    edit: 'Edit',
    remove: 'Remove',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    retry: 'Try again',
    loading: 'Loading…',
    noResults: 'Nothing matches those filters',
    required: 'Required',
    optional: 'Optional',
  },

  /** Signed-out screens: features/auth */
  auth: {
    brand: {
      eyebrow: 'Fleet operations',
      headline: 'Every truck, driver and hour in one place.',
      body: 'Plan the day, keep the fleet legal, and see where everyone is — without chasing paperwork.',
      stats: [
        { label: 'Hours', value: 'Tracked live' },
        { label: 'Inspections', value: 'Filed from the cab' },
        { label: 'Fleet', value: 'On one map' },
      ],
    },

    login: {
      title: 'Sign in',
      subtitle: 'Use the work email your fleet administrator invited.',
      emailLabel: 'Work email',
      emailPlaceholder: 'you@company.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••••',
      forgotLink: 'Forgot password?',
      keepSignedIn: 'Keep me signed in on this computer',
      submit: 'Sign in',
      supportPrefix: 'Trouble signing in?',
      supportLink: 'Contact support',
      errors: {
        emailMissing: 'Enter your work email',
        emailInvalid: 'That does not look like an email address',
        passwordMissing: 'Enter your password',
        passwordTooShort: (min: number) => `Your password is at least ${min} characters`,
        wrongCredentials: 'That email and password do not match. Check both and try again.',
        accountLocked:
          'This account is locked after too many attempts. Ask your fleet administrator to unlock it.',
      },
    },

    forgotPassword: {
      title: 'Reset your password',
      subtitle: 'We will email you a link to set a new one.',
      emailLabel: 'Work email',
      emailPlaceholder: 'you@company.com',
      submit: 'Send reset link',
      backToSignIn: 'Back to sign in',
      errors: {
        emailInvalid: 'Enter the email address you sign in with',
      },
      sent: {
        title: 'Check your email',
        subtitle: (email: string) =>
          `If an account exists for ${email}, a reset link is on its way.`,
        noticeTitle: 'The link expires in one hour',
        noticeBody:
          'Not arrived after a few minutes? Check the spam folder, or ask your fleet administrator to resend the invitation.',
      },
    },

    resetPassword: {
      title: 'Choose a new password',
      subtitle: 'You will use this every time you sign in.',
      passwordLabel: 'New password',
      confirmLabel: 'Confirm new password',
      submit: 'Save password',
      backToSignIn: 'Back to sign in',
      errors: {
        mismatch: 'The two passwords do not match',
      },
      done: {
        title: 'Password saved',
        subtitle: 'Sign in with your new password.',
        cta: 'Go to sign in',
      },
    },

    acceptInvite: {
      title: (org: string) => `Join ${org}`,
      subtitle: 'Set up your account to get started.',
      invitedAs: (role: string) => `You have been invited as a ${role}`,
      signingInWith: 'Signing in with',
      nameLabel: 'Your name',
      namePlaceholder: 'Priya Sharma',
      passwordLabel: 'Create a password',
      submit: 'Create account',
      notExpecting:
        'Not expecting this invitation? Close this page and tell your fleet administrator.',
      errors: {
        nameMissing: 'Enter your name as colleagues will see it',
      },
    },

    /** Shared by every screen that sets a password. */
    password: {
      minLength: 10,
      strengthLabels: ['', 'Weak', 'Fair', 'Good', 'Strong'] as const,
      problems: {
        empty: 'Choose a password',
        tooShort: (min: number) => `Use at least ${min} characters`,
        needsMixedCase: 'Mix upper and lower case letters',
        needsNumber: 'Include at least one number',
      },
    },
  },

  /** Pinned to the bottom of every signed-out screen. */
  authFooter: {
    copyright: (year: number) => `© ${year} B2bSamsaraFleet`,
    privacy: 'Privacy',
    terms: 'Terms',
    status: 'All systems operational',
  },

  /** The signed-in shell: app/layouts/ConsoleLayout */
  console: {
    subtitle: 'Fleet console',
    signOut: 'Sign out',
    accountMenu: 'Account menu',
    accountSettings: 'Account settings',
    orgSettings: 'Organisation settings',
    help: 'Help & support',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    searchPlaceholder: 'Search drivers, vehicles, routes',
    searchPlaceholderCompact: 'Search',
    searchGroups: { drivers: 'Drivers', vehicles: 'Vehicles', routes: 'Routes', staff: 'Users' },
    searchNoResults: (query: string) => `Nothing matches “${query}”`,
    searchHint: 'Type to search across drivers, vehicles, routes and users.',
    searchCount: (n: number) => (n === 1 ? '1 result' : `${n} results`),
    notifications: 'Notifications',
    unreadCount: (n: number) => `${n} unread`,
    notDesignedYet: 'Screens for this module are not designed yet.',
    moduleEyebrow: (id: string) => `Module ${id}`,
    pageNotFound: 'Page not found',
  },

  /** Notifications: features/notifications */
  notifications: {
    title: 'Notifications',
    open: 'Open notifications',
    unreadCount: (n: number) => (n === 1 ? '1 unread' : `${n} unread`),
    markAllRead: 'Mark all as read',
    markRead: 'Mark as read',
    allRead: 'All caught up',
    tabs: { all: 'All', unread: 'Unread' },
    empty: {
      all: 'Nothing here yet. Alerts about hours, defects and expiries will appear as they happen.',
      unread: 'No unread notifications.',
    },
    viewAll: 'View all notifications',
    pageSubtitle: 'Everything the system has flagged, newest first.',
  },

  /** Dashboard: features/dashboard  (module A02) */
  dashboard: {
    title: 'Dashboard',
    greetings: {
      morning: 'Good morning',
      afternoon: 'Good afternoon',
      evening: 'Good evening',
      night: 'Working late',
    },
    liveNow: 'Live',
    openMap: 'Open live map',
    greeting: (greeting: string, name: string) => `${greeting}, ${name.split(' ')[0]}`,
    subtitle: 'Here is what needs attention across the fleet right now.',
    needsAttention: 'Needs attention',
    needsAttentionHint: 'Newest first. Clearing these keeps the fleet legal.',
    recentActivity: 'Recent activity',
    recentActivityHint: 'What your team changed today.',
    viewAll: 'View all',
    allClear: 'Nothing needs attention. The fleet is clear.',
    quickActions: 'Quick actions',
    actions: {
      addDriver: 'Add a driver',
      addVehicle: 'Add a vehicle',
      planRoute: 'Plan a route',
      messageFleet: 'Message the fleet',
    },
  },

  /**
   * Sidebar names for the fifteen admin modules.
   * Keys are the reference codes from the scope document, so a conversation
   * about "A06" means the same thing in the code, the document and the invoice.
   */
  modules: {
    A01: 'Users & access',
    A02: 'Dashboard',
    A03: 'Live map',
    A04: 'Drivers',
    A05: 'Vehicles & maintenance',
    A06: 'Working hours',
    A07: 'Inspections & defects',
    A08: 'Dispatch & routes',
    A09: 'Form builder',
    A10: 'Messages',
    A11: 'Safety & coaching',
    A12: 'Training',
    A13: 'Documents',
    A14: 'Reports',
    A15: 'Settings & audit',
  },

  /** Anything that produces a file. */
  export: {
    csv: 'Export CSV',
    started: (filename: string) => `Downloaded ${filename}`,
    nothingToExport: 'There is nothing to export with these filters.',
  },

  /** Dialogs, forms and confirmations shared across modules. */
  dialog: {
    saved: 'Saved',
    cancel: 'Cancel',
    confirmSignOutTitle: 'Sign out?',
    confirmSignOutMessage:
      'You will need your email and password to get back in. Anything unsaved on this screen is lost.',
    confirmSignOut: 'Sign out',
    required: 'This field is required',
    invalidEmail: 'Enter a valid email address',
  },

  forms_common: {
    addDriverTitle: 'Add a driver',
    addDriverDescription: 'They will appear as off duty until they sign into the app.',
    addDriverSubmit: 'Add driver',
    addDriverToast: (name: string) => `${name} added to the fleet`,
    driverFields: {
      firstName: 'First name',
      lastName: 'Last name',
      employeeNumber: 'Employee number',
      terminal: 'Home terminal',
      email: 'Email',
      phone: 'Phone',
      licenceExpires: 'Licence expires',
    },

    addVehicleTitle: 'Add a vehicle',
    addVehicleDescription: 'Odometer readings are stored in kilometres throughout.',
    addVehicleSubmit: 'Add vehicle',
    addVehicleToast: (name: string) => `${name} added to the fleet`,
    vehicleFields: {
      name: 'Name',
      namePlaceholder: 'Truck 231',
      plate: 'Registration plate',
      makeModel: 'Make & model',
      year: 'Year',
      terminal: 'Home terminal',
      odometer: 'Odometer (km)',
    },

    inviteTitle: 'Invite a user',
    inviteDescription: 'They receive an email with a link to set their password.',
    inviteSubmit: 'Send invitation',
    inviteToast: (email: string) => `Invitation sent to ${email}`,
    inviteFields: { name: 'Name', email: 'Work email', role: 'Role', fleet: 'Fleet' },

    routeTitle: 'Plan a route',
    routeDescription: 'Assign a driver and a vehicle, and set how many stops the run has.',
    routeSubmit: 'Create route',
    routeToast: (ref: string) => `Route ${ref} created`,
    routeFields: {
      driver: 'Driver',
      vehicle: 'Vehicle',
      stops: 'Number of stops',
      startTime: 'Start time',
      notes: 'Notes for the driver',
    },
    routeHoursWarning: (name: string) =>
      `${name} has no driving hours left today. Assigning this route would put them over the limit.`,
    routeHoursConfirmTitle: 'Dispatch anyway?',
    routeHoursConfirmMessage: (name: string) =>
      `${name} has no driving hours left. Creating this route would put them over the limit.`,
    routeHoursConfirm: 'Create route anyway',

    formTitle: 'New form',
    formDescription: 'Create the form. It stays a draft until you publish it.',
    formSubmit: 'Create form',
    formToast: (name: string) => `${name} created as a draft`,
    formFields: { name: 'Form name', assignedTo: 'Assign to' },

    courseTitle: 'New course',
    courseDescription: 'Courses stay a draft until you add content and publish them.',
    courseSubmit: 'Create course',
    courseToast: (name: string) => `${name} created as a draft`,
    courseFields: { name: 'Course name', length: 'Length (minutes)', assignTo: 'Assign to' },
  },

  /** Shared table chrome: pagination and empty states. */
  table: {
    pagination: 'Pagination',
    previous: 'Previous',
    next: 'Next',
    showing: (first: number, last: number, total: number) =>
      `Showing ${first}–${last} of ${total}`,
  },

  empty: {
    /** Nothing exists yet. */
    noneYetTitle: 'Nothing here yet',
    /** A filter or search removed everything. */
    noMatchTitle: 'No matches',
    noMatchHint: 'Try a different search, or clear the filters to see everything.',
    clearFilters: 'Clear filters',
  },

  /** Module screens. One block per module, keyed by its reference code. */
  users: {
    title: 'Users & access',
    description: 'Who can open this console, and what each of them may do.',
    invite: 'Invite a user',
    searchPlaceholder: 'Search by name or email',
    tabs: { all: 'All', active: 'Active', invited: 'Invited', suspended: 'Suspended' },
    columns: { user: 'User', role: 'Role', fleet: 'Fleet', status: 'Status', lastActive: 'Last active' },
    empty: 'No users match those filters.',
    rolesTitle: 'Roles',
    rolesHint: 'What each role can reach. Custom roles can be added.',
    peopleCount: (n: number) => (n === 1 ? '1 person' : `${n} people`),
    back: 'All users',
    notFound: 'That user no longer exists.',
    detail: {
      profile: 'Profile',
      access: 'Access',
      email: 'Email',
      role: 'Role',
      fleet: 'Fleet',
      status: 'Status',
      lastActive: 'Last active',
      permissions: 'What this role can do',
    },
  },

  drivers: {
    title: 'Drivers',
    description: 'Everyone who drives for the fleet, and whether they are legal to do so.',
    add: 'Add a driver',
    searchPlaceholder: 'Search by name or employee number',
    tabs: { all: 'All', driving: 'Driving', on_duty: 'On duty', off_duty: 'Off duty', offline: 'Offline' },
    columns: { driver: 'Driver', terminal: 'Home terminal', status: 'Status', vehicle: 'Vehicle', hoursLeft: 'Hours left', licence: 'Licence expires', score: 'Safety' },
    empty: 'No drivers match those filters.',
    licenceWarning: 'Expiring soon',
    noVehicle: 'Not assigned',
    back: 'All drivers',
    notFound: 'That driver no longer exists.',
    tabsDetail: {
      overview: 'Overview',
      hours: 'Hours',
      inspections: 'Inspections',
      safety: 'Safety',
      documents: 'Documents',
    },
    detail: {
      employment: 'Employment',
      compliance: 'Compliance',
      currentAssignment: 'Current assignment',
      employeeNumber: 'Employee number',
      terminal: 'Home terminal',
      status: 'Duty status',
      hoursLeft: 'Driving hours left',
      licence: 'Licence expires',
      safetyScore: 'Safety score',
      vehicle: 'Vehicle',
      noVehicleHint: 'This driver has not taken a vehicle out.',
      recentLogs: 'Last seven days',
      logGraph: 'Daily log',
      logGraphHint: 'Duty status across 24 hours — the same chart the driver sees on the phone.',
      logStatuses: {
        off: 'Off duty',
        sleeper: 'Sleeper',
        driving: 'Driving',
        on_duty: 'On duty',
      },
      recap: {
        onDuty: 'On duty',
        driving: 'Driving',
        break: 'Break',
        cycle: 'Cycle',
      },
      previousDay: 'Previous day',
      nextDay: 'Next day',
      pickLogDate: 'Choose a log date',
      today: 'Today',
      noInspections: 'No inspections filed by this driver yet.',
      noSafety: 'No safety events recorded for this driver.',
      noDocuments: 'No documents uploaded by this driver yet.',
      message: 'Message driver',
    },
  },

  vehicles: {
    title: 'Vehicles & maintenance',
    description: 'Trucks, trailers and the work needed to keep them on the road.',
    add: 'Add a vehicle',
    searchPlaceholder: 'Search by name or plate',
    tabs: { all: 'All', active: 'Active', in_maintenance: 'In maintenance', out_of_service: 'Out of service' },
    columns: { vehicle: 'Vehicle', makeModel: 'Make & model', status: 'Status', driver: 'Current driver', odometer: 'Odometer', service: 'Next service' },
    empty: 'No vehicles match those filters.',
    back: 'All vehicles',
    notFound: 'That vehicle no longer exists.',
    detail: {
      identity: 'Identity',
      condition: 'Condition',
      plate: 'Registration plate',
      makeModel: 'Make & model',
      year: 'Year',
      status: 'Status',
      driver: 'Current driver',
      odometer: 'Odometer',
      nextService: 'Next service',
      openWorkOrders: 'Open work orders',
      noWorkOrders: 'No repair jobs open for this vehicle.',
      recentInspections: 'Recent inspections',
      noInspections: 'No inspections filed for this vehicle yet.',
    },
    overdueBy: (km: number) => `Overdue by ${km.toLocaleString()} km`,
    dueIn: (km: number) => `Due in ${km.toLocaleString()} km`,
    unassigned: 'Unassigned',
    workOrders: 'Work orders',
    workOrdersHint: 'Repairs raised from defects, schedules or by hand.',
    woColumns: { reference: 'Reference', vehicle: 'Vehicle', job: 'Job', status: 'Status', mechanic: 'Mechanic', opened: 'Opened' },
    woBack: 'All vehicles',
    woNotFound: 'That work order no longer exists.',
    woDetail: {
      about: 'Work order',
      reference: 'Reference',
      vehicle: 'Vehicle',
      job: 'Job',
      status: 'Status',
      mechanic: 'Mechanic',
      opened: 'Opened',
      cost: 'Cost so far',
      openVehicle: 'Open vehicle',
    },
  },

  hours: {
    title: 'Working hours',
    description: 'Driver logs, breaches and the corrections waiting on a decision.',
    exportPack: 'Export audit pack',
    gridTitle: 'Log review',
    gridHints: {
      day: 'One day. Colour marks anything not certified.',
      week: 'Monday to Sunday. Colour marks anything not certified.',
      month: 'Every day in the month. Scroll sideways if you need to.',
    },
    period: { day: 'Day', week: 'Week', month: 'Month' },
    periodAria: 'Log review period',
    previousPeriod: { day: 'Previous day', week: 'Previous week', month: 'Previous month' },
    nextPeriod: { day: 'Next day', week: 'Next week', month: 'Next month' },
    pickDate: 'Choose a date',
    pickMonth: 'Choose a month',
    jumpToToday: 'Today',
    violationsTitle: 'Violations',
    violationsHint: 'Every breach of the working-hours rules, newest first.',
    editRequestsTitle: 'Correction requests',
    editRequestsHint: 'A driver has asked to change a past log. Approving pushes the change to their phone.',
    unassignedTitle: 'Unassigned driving',
    unassignedHint: 'Driving recorded with no driver signed in. Assign it or annotate it.',
    approve: 'Approve',
    reject: 'Reject',
    assign: 'Assign',
    review: 'Review',
    noViolations: 'No violations in this period.',
    allViolationsReviewed: 'Every violation in this period has been reviewed.',
    noEditRequests: 'No corrections waiting on a decision.',
    noUnassigned: 'All driving time is accounted for.',
    reviewViolationTitle: 'Review this violation',
    reviewViolationHint: 'Check the details, then approve if this is a real breach or reject it if it is not.',
    reviewCorrectionTitle: 'Review this correction',
    reviewCorrectionHint:
      'A driver asked to change a past log. Approving sends the change to their phone — you cannot edit the log yourself.',
    fields: {
      driver: 'Driver',
      vehicle: 'Vehicle',
      rule: 'Rule',
      occurred: 'Recorded',
      logDate: 'Log date',
      limit: 'Limit',
      actual: 'What happened',
      overage: 'Over by',
      location: 'Where',
      loggedAs: 'Currently logged as',
      changeTo: 'Asked to change to',
      timeBlock: 'Time block',
      reason: 'Driver’s reason',
      kind: 'Request',
    },
    requestKinds: {
      change: 'Change an existing block',
      add: 'Add a missing block',
    },
    timeRange: (from: string, to: string) => `${from} – ${to}`,
    statusChange: (from: string, to: string) => `${from} → ${to}`,
    violationDecisionNote:
      'Approving records that this is a real breach. Rejecting dismisses it as not a violation. The original log is unchanged either way.',
    correctionDecisionNote: (driver: string) =>
      `Approving sends the change to ${driver}’s phone — they must accept it before the log is updated. Rejecting leaves the original log unchanged.`,
    approvedViolationToast: 'Violation confirmed',
    dismissedViolationToast: 'Violation dismissed',
    approvedToast: 'Correction sent to the driver',
    rejectedToast: 'Correction rejected',
    assignedToast: (driver: string) => `Assigned to ${driver}`,
    assignTitle: 'Assign this driving time',
    assignHint: 'Choose the driver who was behind the wheel. This attaches the segment to their log.',
    assignSubmit: 'Assign to driver',
    assignDriver: 'Driver',
    confirmExportTitle: 'Export the audit pack?',
    confirmExportMessage: 'A spreadsheet of every driver and day in this period will download now.',
    confirmExport: 'Export',
    legend: 'Legend',
  },

  inspections: {
    title: 'Inspections & defects',
    description: 'What drivers found when they walked around the vehicle.',
    searchPlaceholder: 'Search by vehicle or driver',
    tabs: { all: 'All', open_defect: 'Open defects', pending: 'Awaiting review', resolved: 'Resolved' },
    columns: { vehicle: 'Vehicle', driver: 'Driver', type: 'Type', submitted: 'Submitted', defects: 'Defects', status: 'Status' },
    empty: 'No inspections match those filters.',
    noDefects: 'None',
    back: 'All inspections',
    notFound: 'That inspection no longer exists.',
    detail: {
      summary: 'Inspection',
      defectsTitle: 'Defects',
      defectsHint: 'Found on the walk-around. Safety-critical items stop the vehicle.',
      noDefects: 'No defects recorded on this inspection.',
      vehicle: 'Vehicle',
      driver: 'Driver',
      type: 'Type',
      submitted: 'Submitted',
      status: 'Status',
      area: 'Area',
      finding: 'Finding',
      severity: 'Severity',
      openVehicle: 'Open vehicle',
      openDriver: 'Open driver',
      openStaff: 'Open profile',
    },
  },

  map: {
    title: 'Live map',
    description: 'Where every vehicle is right now.',
    vehiclesOnMap: (n: number) => `${n} vehicles`,
    schematicNote: 'Schematic view',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    recentre: 'Centre on the fleet',
    mapTypes: { roadmap: 'Standard', satellite: 'Satellite', hybrid: 'Hybrid', terrain: 'Terrain' },
    mapTypeLabel: 'Map view',
    noKeyTitle: 'Google Maps is not configured',
    noKeyHint:
      'Add VITE_GOOGLE_MAPS_API_KEY to .env.local and restart the dev server to replace this with a live map. Everything else on this screen already works.',
    lastPing: 'Last ping',
    speed: 'Speed',
    openDriver: 'Open driver',
    stationary: 'Stationary',
    openVehicle: 'Open vehicle',
    location: 'Location',
  },

  dispatch: {
    title: 'Dispatch & routes',
    description: "Today's work, who is doing it, and whether it is running to time.",
    newRoute: 'Plan a route',
    searchPlaceholder: 'Search by route, driver or vehicle',
    tabs: { all: 'All', in_progress: 'In progress', late: 'Running late', planned: 'Planned', completed: 'Completed' },
    columns: { route: 'Route', driver: 'Driver', vehicle: 'Vehicle', progress: 'Stops', status: 'Status', eta: 'Timing' },
    empty: 'No routes match those filters.',
    stopsOf: (done: number, total: number) => `${done} of ${total}`,
    back: 'All routes',
    notFound: 'That route no longer exists.',
    detail: {
      assignment: 'Assignment',
      progress: 'Progress',
      driver: 'Driver',
      vehicle: 'Vehicle',
      status: 'Status',
      timing: 'Timing',
      stopsTitle: 'Stops',
      stopsHint: 'In the order the driver will visit them.',
      stopDone: 'Completed',
      stopNext: 'Next stop',
      stopPending: 'Not started',
      arrived: 'Arrived',
      window: 'Window',
      viewOnMap: 'View on map',
      messageDriver: 'Message driver',
    },
  },

  forms: {
    title: 'Form builder',
    description: 'Build the paperwork your drivers fill in, without waiting for a developer.',
    newForm: 'New form',
    columns: { form: 'Form', fields: 'Fields', version: 'Version', status: 'Status', assigned: 'Assigned to', submissions: 'Submissions', updated: 'Updated' },
    empty: 'No forms yet.',
    fieldTypesTitle: 'Available field types',
    fieldTypesHint: 'These field types appear on the phone. Open a form to see them in use.',
    back: 'All forms',
    notFound: 'That form no longer exists.',
    detail: {
      about: 'About this form',
      fieldsTitle: 'Fields',
      fieldsHint: 'In the order the driver sees them on the phone.',
      name: 'Name',
      version: 'Version',
      status: 'Status',
      assigned: 'Assigned to',
      submissions: 'Submissions',
      updated: 'Last updated',
      required: 'Required',
      optional: 'Optional',
    },
  },

  messages: {
    title: 'Messages',
    description: 'Every conversation with every driver, in one inbox.',
    broadcast: 'Message the fleet',
    searchPlaceholder: 'Search conversations',
    empty: 'No conversations yet.',
    selectThread: 'Choose a conversation to read it.',
    composePlaceholder: 'Write a message',
    send: 'Send',
    sentToast: (driver: string) => `Message sent to ${driver}`,
    broadcastTitle: 'Message the fleet',
    broadcastDescription: 'Goes to every driver you select, as a push notification and an in-app message.',
    broadcastSubmit: 'Send to fleet',
    broadcastToast: (n: number) => `Message sent to ${n} ${n === 1 ? 'driver' : 'drivers'}`,
    broadcastFields: { audience: 'Send to', message: 'Message' },
    broadcastAudience: {
      all: 'Every driver',
      pune: 'Pune depot only',
      nashik: 'Nashik depot only',
      onDuty: 'Drivers on duty right now',
    },
    broadcastEmpty: 'Write something to send.',
    backToInbox: 'All conversations',
    newThreadPreview: 'No messages yet — write the first one.',
  },

  safety: {
    title: 'Safety & coaching',
    description: 'Incidents recorded on the road, and what was done about them.',
    tabs: { all: 'All', new: 'Needs review', coachable: 'Coaching assigned', dismissed: 'Dismissed' },
    columns: { driver: 'Driver', event: 'Event', severity: 'Severity', location: 'Location', at: 'When', status: 'Status' },
    empty: 'No events match those filters.',
    assignCoaching: 'Assign coaching',
    dismiss: 'Dismiss',
    confirmCoachTitle: 'Assign coaching?',
    confirmCoachMessage: (driver: string, kind: string) =>
      `${driver} gets a coaching task about this ${kind.toLowerCase()} on their phone, and must acknowledge it.`,
    confirmCoach: 'Assign coaching',
    coachedToast: (driver: string) => `Coaching assigned to ${driver}`,
    confirmDismissTitle: 'Dismiss this event?',
    confirmDismissMessage:
      'It stays in the safety record but stops counting towards the driver\'s score and needs no action.',
    confirmDismiss: 'Dismiss event',
    dismissedToast: 'Event dismissed',
    scoreboardTitle: 'Safety scoreboard',
    scoreboardHint: 'Highest scores this month.',
    back: 'All events',
    notFound: 'That event no longer exists.',
    detail: {
      about: 'Event',
      driver: 'Driver',
      kind: 'What happened',
      severity: 'Severity',
      location: 'Location',
      at: 'When',
      status: 'Status',
      openDriver: 'Open driver',
    },
  },

  training: {
    title: 'Training',
    description: 'Short courses assigned to drivers, and who still owes you one.',
    newCourse: 'New course',
    columns: { course: 'Course', length: 'Length', assigned: 'Assigned', completed: 'Completed', overdue: 'Overdue', status: 'Status' },
    empty: 'No courses yet.',
    minutes: (n: number) => `${n} min`,
    back: 'All courses',
    notFound: 'That course no longer exists.',
    detail: {
      about: 'Course',
      learnersTitle: 'Assigned drivers',
      learnersHint: 'Who still owes you this course.',
      length: 'Length',
      assigned: 'Assigned',
      completed: 'Completed',
      overdue: 'Overdue',
      status: 'Status',
      learnerStatus: {
        completed: 'Completed',
        overdue: 'Overdue',
        in_progress: 'In progress',
        not_started: 'Not started',
      },
    },
  },

  documents: {
    title: 'Documents',
    description: 'Paperwork captured from the cab, filed and searchable.',
    searchPlaceholder: 'Search by file, driver or vehicle',
    exportAll: 'Export selection',
    confirmExportTitle: 'Export documents?',
    confirmExportMessage: (n: number) =>
      `${n} ${n === 1 ? 'document' : 'documents'} will be packaged as a ZIP and emailed to you when it is ready.`,
    confirmExport: 'Start export',
    exportToast: 'Export started — you will get an email when it is ready',
    tabs: { all: 'All', bol: 'Bills of lading', pod: 'Proof of delivery', receipt: 'Receipts', fuel: 'Fuel dockets' },
    columns: { file: 'File', kind: 'Type', driver: 'Driver', vehicle: 'Vehicle', uploaded: 'Uploaded', size: 'Size' },
    empty: 'No documents match those filters.',
    back: 'All documents',
    notFound: 'That document no longer exists.',
    detail: {
      about: 'File',
      preview: 'Preview',
      previewHint: 'Captured from the cab. A real file would open here.',
      file: 'File name',
      kind: 'Type',
      driver: 'Driver',
      vehicle: 'Vehicle',
      uploaded: 'Uploaded',
      size: 'Size',
      openDriver: 'Open driver',
      openVehicle: 'Open vehicle',
      download: 'Download',
    },
  },

  reports: {
    title: 'Reports',
    description: 'Eleven standard reports. Filter by depot, then export a spreadsheet.',
    run: 'Run',
    lastRun: (when: string) => `Last run ${when.toLowerCase()}`,
    depotAria: 'Depot',
    depots: { all: 'All depots', pune: 'Pune depot', nashik: 'Nashik depot' },
    scheduleTitle: 'Scheduled delivery',
    scheduleHint: 'Send a report by email on a schedule, so nobody has to remember to run it.',
  },

  settings: {
    title: 'Settings & audit',
    description: 'How the organisation is configured, and a record of every change.',
    orgTitle: 'Organisation',
    orgHint: 'Name and branding, used here and in the driver app.',
    alertsTitle: 'Alert rules',
    alertsHint: 'Who gets told, and when.',
    auditTitle: 'Audit log',
    auditHint: 'Every change made in this console, with who made it. Required for audits.',
    auditColumns: { who: 'Who', action: 'Action', target: 'What', at: 'When' },
    channels: 'Channels',
    on: 'On',
    off: 'Off',
    fields: { name: 'Organisation name', country: 'Country', timezone: 'Timezone', dot: 'Regulator number' },
    saveOrg: 'Save organisation',
    savedToast: 'Organisation saved',
    alertOnToast: (name: string) => `${name} alerts are on`,
    alertOffToast: (name: string) => `${name} alerts are off`,
    turnOn: 'Turn on',
    turnOff: 'Turn off',
  },

  help: {
    title: 'Help & support',
    description: 'How this console works, and who to contact when something is wrong.',
    contactTitle: 'Contact support',
    contactHint: 'A person reads this. Include the organisation name and what you were doing.',
    emailLabel: 'Email',
    email: 'support@example.com',
    hoursLabel: 'Hours',
    hours: 'Monday–Saturday, 8:00–20:00 IST',
    replyLabel: 'Typical reply',
    reply: 'Same working day',
    emailCta: 'Write to support',
    guidesTitle: 'How the console works',
    guidesHint: 'The few things that are easy to get wrong.',
    guides: [
      {
        title: 'Search from the top of any page',
        body: 'Type a driver, vehicle, route or user. Results are grouped so you can tell which is which.',
      },
      {
        title: 'Open a row for the full record',
        body: 'Lists are summaries. Click a driver, vehicle, inspection or violation to see every field and take an action.',
      },
      {
        title: 'Review is a decision, not a tick',
        body: 'On working hours, Review opens the details. Approve confirms the breach or sends a log change to the driver’s phone. Reject leaves the original log as it is.',
      },
      {
        title: 'You cannot edit a driver’s log',
        body: 'A carrier may not change a driver’s record on their behalf. Approving a correction request sends it to their phone for them to accept.',
      },
    ],
    topicsTitle: 'Jump to a module',
    topicsHint: 'Open the screen instead of hunting for it in the sidebar.',
    topics: [
      { to: '/hours', title: 'Working hours', body: 'Logs, violations and correction requests.' },
      { to: '/inspections', title: 'Inspections', body: 'Walk-around findings and open defects.' },
      { to: '/drivers', title: 'Drivers', body: 'People, licences and hours remaining.' },
      { to: '/vehicles', title: 'Vehicles', body: 'The fleet, service due and work orders.' },
      { to: '/dispatch', title: 'Dispatch', body: 'Today’s routes and who is on them.' },
      { to: '/messages', title: 'Messages', body: 'Conversations with drivers, and a fleet broadcast.' },
      { to: '/safety', title: 'Safety', body: 'Events from the road and coaching assigned.' },
      { to: '/settings', title: 'Settings', body: 'Organisation, alert rules and the audit log.' },
    ],
  },

  /** Sidebar section headings. */
  moduleGroups: {
    Overview: 'Overview',
    Fleet: 'Fleet',
    Compliance: 'Compliance',
    Operations: 'Operations',
    People: 'People',
    Admin: 'Admin',
  },
} as const

export type Strings = typeof STRINGS
