-- ============================================================================
-- Messaging  (1 table)   -- admin module A11
-- ============================================================================
-- Office-to-driver messages.
--
-- No message_threads table. A conversation here is always between the office
-- and one driver, so driver_id already identifies the thread - a separate
-- table would hold one row per driver and nothing else, and every read would
-- join through it to learn what driver_id already said.
--
-- A message sent to the whole fleet is one row per driver sharing a
-- broadcast_id. That costs more rows than a single broadcast record, and buys
-- the thing that matters: each driver's copy has its own read receipt, and the
-- conversation view needs no union of two sources.
-- ============================================================================


create type public.message_direction as enum (
  'to_driver',
  'from_driver'
);


-- ---------------------------------------------------------------------------
-- messages
-- ---------------------------------------------------------------------------

create table public.messages (
  id            uuid primary key default gen_random_uuid(),
  org_id        uuid        not null references public.organizations(id) on delete cascade,

  -- Whose conversation this is. Not "the recipient" - an inbound message from
  -- this driver belongs to the same conversation.
  driver_id     uuid        not null references public.drivers(id) on delete cascade,

  direction     public.message_direction not null,

  -- Who in the office sent it. Null on inbound messages, and on outbound ones
  -- generated by the system rather than a person.
  sender_user_id uuid references public.users(id) on delete set null,

  body          text        not null,
  attachment_path text,

  sent_at       timestamptz not null default now(),
  read_at       timestamptz,

  -- Set on every copy of a fleet-wide message, so the office can see it as one
  -- send rather than forty.
  broadcast_id  uuid,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz,

  constraint messages_body_not_blank check (length(btrim(body)) > 0),
  -- A driver's own message cannot have been sent by a member of office staff.
  constraint messages_inbound_has_no_staff_sender check (
    direction = 'to_driver' or sender_user_id is null
  )
);

comment on table public.messages is
  'Office-to-driver conversation. driver_id is the thread; broadcast_id groups the copies of a fleet-wide send.';

comment on column public.messages.broadcast_id is
  'Shared by every copy of one fleet-wide message, so each driver still gets their own read receipt.';

create index messages_conversation_idx on public.messages (driver_id, sent_at desc)
  where deleted_at is null;
create index messages_org_idx          on public.messages (org_id, sent_at desc)
  where deleted_at is null;
create index messages_broadcast_idx    on public.messages (broadcast_id)
  where broadcast_id is not null;

-- The unread badge.
create index messages_unread_idx on public.messages (org_id, driver_id)
  where read_at is null and deleted_at is null;

create trigger messages_set_updated_at before update on public.messages
  for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------

alter table public.messages enable row level security;

create policy messages_select_org on public.messages
  for select to authenticated
  using ((select public.is_super_admin()) or org_id in (select public.current_org_ids()));

create policy messages_select_self on public.messages
  for select to authenticated
  using (driver_id = (select public.current_driver_id()));

-- A driver may write into their own conversation, inbound only. Without the
-- direction check they could post a message that looks like it came from the
-- office.
create policy messages_insert_self on public.messages
  for insert to authenticated
  with check (
    driver_id = (select public.current_driver_id())
    and direction = 'from_driver'
    and sender_user_id is null
  );

-- Marking a message read is the only thing a driver may change.
create policy messages_mark_read_self on public.messages
  for update to authenticated
  using (driver_id = (select public.current_driver_id()))
  with check (driver_id = (select public.current_driver_id()));

create policy messages_write on public.messages
  for all to authenticated
  using ((select public.has_org_role(org_id, array['fleet_admin','dispatcher'])))
  with check ((select public.has_org_role(org_id, array['fleet_admin','dispatcher'])));


-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

grant select, insert, update, delete on public.messages to authenticated;
